### ISSUE TITLE
Duplication of samples if internet drops

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#180]
I'm not sure if anything can be done about this, but one of the sites does not have great internet connection. A project member creating some practice samples made 3 aliquots, but the system created 6, likely because of the internet connection. 

Whilst we are practicing, it is not a big deal. With real samples, I would usually go in and delete them.

I'm just wondering if there is anything that can be done your end to reduce the likelihood of this happening?

![image](https://user-images.githubusercontent.com/98022410/154082022-f8c3c765-c133-4f46-a135-149ccbf55a9c.png)

**Comment by pipaLU** [comment]
This is a known problem, will take a look at it again how to stop from the client side sending duplicate requests.

**Comment by KeironO** [comment]
As most stuff is broken out into API endpoints, we could just start using Celery for task management. This is a bit of a 'project' in itself, and it'll involve:

- Setting up Celery
- Configuring calls so that they allow for async.
- Writing a way for users to 'inspect' their tasks, so they don't submit twice.
- Telling users that they need to check that a task has been submitted/completed when they experience connectivity issues

**Comment by KeironO** [comment]
I take that as a yes.
